version: '3'

services:
  social_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: social_py
  social_web:
    container_name: djsocial
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/djsocial_site
    ports:
      - "8000:8000"
    depends_on:
      - social_db

volumes:
  postgres_data: